name: CI

on: pull_request

jobs:
  build:
    name: ${{ matrix.task }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust: ['1.60.0']
        task: [check, fmt, clippy, test]
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies (windows only)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static-md
          echo "::set-env OPENSSL_DIR 'C:\Tools\vcpkg\installed\x64-windows-static-md'"
          echo "::set-env OPENSSL_STATIC Yes"
        env:
          VCPKG_ROOT: 'C:\vcpkg'

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
  
      - name: ${{ matrix.task }}
        run: make ${{ matrix.task }}
